### ISSUE TITLE
Add comment below code panel

### ISSUE THREAD

**Issue by stunited-thien** [DarkTrick/SourceCodeVisualizer#12]
Hi, I have a complex personal project that needs to be shared with my mentor. He needs me to create code documentation. Can you add the comment feature kind of like how the Code Diagram extension uses markdown to provide comment in vscode
![image](https://github.com/DarkTrick/SourceCodeVisualizer/assets/145310180/bbeb387d-3390-4591-9a20-8098b37a4818)

**Comment by DarkTrick** [comment]
Thank you very much for the suggestion. However, this project aims for integrated development, not documentation. Therefore the feature you ask for won't be implemented in that very form.

However, I'm still working on how docstring comments ought to be represented in the diagram. Maybe that might be a feature you could use instead. 
But even then, I currently have no time working on the project, so whatever is going to happen, it will need some time to be implemented.
